### ISSUE TITLE
Component content audit [progress tracker]

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#411] opened 2022-07-20 15:15 UTC
This component will merge the timeline and progress block with 2 variations.

**Comment by ashleydraper** [comment] 2022-08-03 22:58
This [draft](https://docs.google.com/document/d/1Z7hz_BBI8itBOXGGcF6Fmlf8SMVz-_35jfhfncIkg9I/edit#)is ready for Art and Christina's review. Assigning to Art and Christina.

**Comment by extinah** [comment] 2022-09-20 22:08
@ashleydraper  we did an initial review. requires a quick meeting to discuss some comments.

**Comment by extinah** [comment] 2022-09-20 22:10
Thinking to make the step list a content patterns instead. And use progress bar as the component. We can discuss - thanks!

**Comment by yesenia-gtz** [comment] 2022-09-21 23:16
Updates:

**Comment by extinah** [comment] 2022-09-21 23:30
@kkoryaka  
Per Courtney: Konstantin, it looks like there is an outlined and a filled option for the horizontal version. Can we add that for the vertical version?

Also, in mobile the horizontal version should look more like the step list. Right now if just shows an unlinked circle above the heading with no visual connection. Also, can we add some options for the end circle rather than just a blank circle?

**Comment by ashleydraper** [comment] 2022-10-04 23:17
Here is the finalized [staging document](https://docs.google.com/document/d/1Z7hz_BBI8itBOXGGcF6Fmlf8SMVz-_35jfhfncIkg9I/edit#).

**Comment by ashleydraper** [comment] 2022-10-12 19:43
![image](https://user-images.githubusercontent.com/62437425/195433567-f8fdbd23-da0b-4fa4-bdb8-ab93232c658e.png)

**Comment by ashleydraper** [comment] 2022-10-12 19:44
@timothyshambra You can copy that text here.

Step 1. Briefly discuss the step or identify the milestone.
Step 2. Keep the message clear and concise. 
Step 3. Do not use the tracker to link to more information.
Step 4. Link to additional information in your body content or tracker caption.

**Comment by ashleydraper** [comment] 2022-10-12 19:52
![image](https://user-images.githubusercontent.com/62437425/195435022-9eeb4b30-98ec-4105-a7a4-2c96078e76fb.png)

**Comment by ashleydraper** [comment] 2022-10-12 20:02
![image](https://user-images.githubusercontent.com/62437425/195436845-4f58ec3a-644f-4f31-af51-9d734099ed4a.png)

**Comment by ashleydraper** [comment] 2022-10-12 20:03
### Give your steps a clear, concise title
The step list is a good fit for lengthy content. Use this space to discuss the step or identify the milestone. If there is information that your visitor must know before completing this step, you can talk about that here too.

### Make your steps actionable
Be sure to tell your visitor exactly what they have to do to complete the step. If the process is not fully fleshed out, then this component may not be the best fit for your content. 

### Conclude the process
All good things must come to an end. Tell your reader how to complete their task. If needed, you can link to additional information in the step list content.

**Comment by ashleydraper** [comment] 2022-10-12 20:06
![image](https://user-images.githubusercontent.com/62437425/195437508-43bd3fa8-cfba-442e-9e84-b78cecaf80a5.png)

**Comment by ashleydraper** [comment] 2022-10-12 23:11
![image](https://user-images.githubusercontent.com/62437425/195464325-3ae2f8e0-5ec0-4b3d-8ebb-cdfbb8ec6200.png)

**Comment by yesenia-gtz** [comment] 2022-10-21 16:38
@timothyshambra  please review the attached recording. 

- I noticed the line element on vertical tracker goes away on smaller device sizes. 
- Menu drop down activated when viewing a smaller screen.

Can this be corrected?

**Link to recording:**
https://www.loom.com/share/eb0277bac5374bee8439835c7958f2b1

Cc @sharon-rabang

**Comment by timothyshambra** [comment] 2022-10-21 16:57
> @timothyshambra please review the attached recording.
> 
> * I noticed the line element on vertical tracker goes away on smaller device sizes.
> * Menu drop down activated when viewing a smaller screen.
> 
> Can this be corrected?
> 
> **Link to recording:** https://www.loom.com/share/eb0277bac5374bee8439835c7958f2b1
> 
> Cc @sharon-rabang

@yesenia-gtz 
1. If we add a vertical line, It would go through the text and decrease legibility. I was not a part of the design of that component, but can look into it further.
2. I was not able to replicate that behavior on my end. Does it keep happening on your end?

**Comment by sharon-rabang** [comment] 2022-10-24 17:30
@timothyshambra Hi! Can you provide the link to this in staging? Thanks!

**Comment by ashleydraper** [comment] 2022-10-24 17:45
Hey @timothyshambra, I have now rolled off of the state template project. Sharon is completing all UX review, so feel free to just assign to her.
Cc: @sharon-rabang

**Comment by sharon-rabang** [comment] 2022-10-24 18:15
@timothyshambra Here are some changes to make and some suggestions for consideration:

Content: Add these bullets after the first sentence on the page.
Use the progress tracker to show:
- Milestones
- Timelines
- Chronological steps 

Responsive view
@timothyshambra @yesenia-gtz It looks like the timeline was designed to display without the line element in responsive view to begin with in https://template.webstandards.ca.gov/sample/timeline.html.
- Horizontal tracker, responsive: The centered content looks okay without the line element because there are dot elements to visually guide you down to the next step.
- Vertical tracker, responsive: The left-aligned content does not have the dot elements to visually guide you through the steps. Is it possible to apply the same code used in the Step list? This may allow us to include the dot and line elements along the left side of the content.

**Comment by sharon-rabang** [comment] 2022-11-19 00:23
11.18.22 Stand-up notes for [#760](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/760): As a mobile view design solution for the horizontal tracker displayed on desktop, try coding it to display as a vertical tracker (left-aligned) when viewed on mobile.

Here are the homepage examples in Figma:
- [Desktop: Horizontal tracker](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A441&t=5FrWSRnN8WnHjo18-1) Keep as is.
- [Mobile: Vertical tracker](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1442%3A13133&t=5FrWSRnN8WnHjo18-1) Use this vertical design for mobile view of the desktop's horizontal tracker design.

**Comment by yesenia-gtz** [comment] 2022-12-14 22:26
@sharon-rabang  this is ready for your review

**Comment by extinah** [comment] 2022-12-19 16:56
@timothyshambra can you give a summary of what you did? Also, when you move to UX QA, please assign to either the main designer, me, or yesenia. appreciate it!

**Comment by sharon-rabang** [comment] 2022-12-20 19:29
> @timothyshambra can you give a summary of what you did? Also, when you move to UX QA, please assign to either the main designer, me, or yesenia. appreciate it!

@timothyshambra I'm reassigning this to you in "Dev - In progress" for an update on your explorations. Please assign back to UX for review or to work with you on resolving the mobile views. Thanks!

**Comment by yesenia-gtz** [comment] 2022-12-22 23:19
@timothyshambra  ok to close this out?

cc @extinah

**Comment by yesenia-gtz** [comment] 2022-12-22 23:34
This is done @extinah

**Comment by extinah** [comment] 2022-12-22 23:55
@timothyshambra There are still some mobile issues. We can work on this in the separate mobile issue for progress track #1072. 

Approved for go-live, with known issues. Thanks!

**Closed** 2022-12-22 23:55 UTC
Labels: eng, content, P2
