### ISSUE TITLE
Create  CSS Style shortcuts page

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#526] opened 2022-10-03 23:33 UTC
Create a CSS Style shortcuts landing page.
Added 10/19 by christina:

- [ ] Work on CSS IA (it needs a better home)

**Comment by yesenia-gtz** [comment] 2022-10-13 23:15
@artuoma  are we able to move this page over as is?

https://template.webstandards.ca.gov/shortcuts.html

**Comment by sharon-rabang** [comment] 2022-10-27 16:56
Closing this issue since this is duplicate of the work in progress in [#663](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/663).

**Closed** 2022-10-27 16:56 UTC
Labels: content, P3
