### ISSUE TITLE
Add pagination component

### ISSUE THREAD

**Issue by ashleydraper** [Office-of-Digital-Services/California-State-Web-Template-Website#514] opened 2022-09-28 22:53 UTC

**Comment by yesenia-gtz** [comment] 2022-11-09 19:40
Needs:
- [ ]  Design recommendation to mirror design system https://designsystem.webstandards.ca.gov/components/pagination/readme/
- [ ] figma layout
- [ ] content guidelines

**Comment by yesenia-gtz** [comment] 2022-12-02 19:30
Moving to backlog as we may not be ready to include in Production release.

**Comment by sharon-rabang** [comment] 2022-12-03 00:12
12/02/22 Comments from [#340](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/issues/340):
@Greg-Watanabe - FYI @extinah and I are still working on the pagination design you're inquiring about. We'll let you know when our proposed pagination design and behaviors are ready for your feedback.

In the meantime, here are some content changes to make to the icon's page to simplify it further:
[Icons - Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1679%3A17045&t=CBCBzdXCI3cljNPk-1)
[Icons- Google Doc](https://docs.google.com/document/d/1LbgcENsfG_AgQ2sNEjJCtHTl4JxCoBe6hrsyXIAayIQ/edit#)

Let us know when the content changes are ready for review. Thanks!

**Comment by sharon-rabang** [comment] 2022-12-06 23:24
@kkoryaka When time permits, please take a look at the Pagination page's rough draft for the Sample "Implementation notes" tab at the end of the Google doc: [Pagination](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#)

We need help identifying what to include, and if the content actually belongs under "Implementation notes". Thanks!

**Comment by extinah** [comment] 2022-12-13 23:33
@sharon-rabang let's work on this next. It's a P1. Thanks!

**Comment by sharon-rabang** [comment] 2022-12-15 19:53
@extinah @ashleydraper @hamiltonryan 
Hi! The Pagination page's design and content are ready for your UX internal review. It's the first time we're describing a component's behaviors with specific guidelines and examples.

Note: This page will need to get updated when the "pagination with inline select" version at the top of the Icons page in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A19464&t=tkxe5z7E279iVRxt-1) gets developed for next release. 

Pagination links:
- [Google doc - Pagination](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#) (Add feedback in doc)
- [Figma - Pagination](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1537%3A14837&t=tkxe5z7E279iVRxt-1) (Add comments in Figma)
- [Sample - Implementation notes](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2272%3A17637&t=tkxe5z7E279iVRxt-1) (Konstantin reviewing content)
- [Pagination: Design concept](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2272%3A17638&t=tkxe5z7E279iVRxt-1) (For visual reference: Screenshot that illustrates how the pagination design compliments its surrounding elements.)

**Comment by extinah** [comment] 2022-12-16 01:06
Good to me :)

**Comment by ashleydraper** [comment] 2022-12-16 17:21
Thanks for sharing @sharon-rabang. Left some comments and edits in the doc.

**Comment by extinah** [comment] 2023-01-05 20:57
@sharon-rabang picking this back up again. Is this ready for the leads review?

**Comment by sharon-rabang** [comment] 2023-01-06 22:28
@extinah It looks like @kkoryaka was in the middle of reviewing, or still has yet to review, the Implementation notes. 
We can move this forward for the leads review and mention that the Implementation notes aren't ready yet. What do you think?

**Comment by extinah** [comment] 2023-01-10 01:01
@sharon-rabang I think that works so this keeps moving forward. I added an item to the list of tasks for implementation notes.

**Comment by sharon-rabang** [comment] 2023-01-10 15:49
@extinah @artuoma @kkoryaka @yesenia-gtz
Hi! The Pagination page's design and content are ready for your lead review. It's the first time we're describing a component's behaviors with specific guidelines and examples.

Note: This page will need to get updated when the "pagination with inline select" version at the top of the Icons page in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1927%3A19464&t=tkxe5z7E279iVRxt-1) gets developed for next release.

Pagination links:
[Google doc - Pagination](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#) (Add feedback in doc)
[Figma - Pagination](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=1537%3A14837&t=tkxe5z7E279iVRxt-1) (Add comments in Figma)
[Sample - Implementation notes](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2272%3A17637&t=tkxe5z7E279iVRxt-1) (Konstantin reviewing content)
[Pagination: Design concept](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2272%3A17638&t=tkxe5z7E279iVRxt-1) (For visual reference: Screenshot that illustrates how the pagination design compliments its surrounding elements.)

**Comment by yesenia-gtz** [comment] 2023-01-11 19:23
@artuoma please review when you are able.

**Comment by artuoma** [comment] 2023-03-01 16:23
Design looks good - my only concern in with "Project Installation" - how are we packaging this? Meaning, this should just work plug and play without the developer needing to install any packages or mess with npm. I agree with @rkojik that we need to create variables where appropriate for pagination for ease of use and better integration into CAWeb.

Would like to have a chat with the DEV team on this @carterm - I am afraid we are focusing too much on how this works using 11ty and for the sample website - instead of a core HTML/CSS/JS environment. We cannot assume people will be in the same environment. Let's chat more on the technical implementation!

**Comment by extinah** [comment] 2023-03-01 16:49
@sharon-rabang can you set up a meeting with dev on this? We can listen in, but not sure how much we can help.

**Comment by sharon-rabang** [comment] 2023-03-01 23:46
@Greg-Watanabe Please review and revise the draft Implementation notes in the [google doc](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#).

**Comment by kkoryaka** [comment] 2023-03-17 20:28
@sharon-rabang this is now updated https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/pagination.html

**Comment by sharon-rabang** [comment] 2023-03-17 22:54
@kkoryaka Thanks! Here are some fixes to make and some questions:
![image](https://user-images.githubusercontent.com/99768807/226064325-fd03d98d-170f-4bfa-9670-0606cfb116e3.png)

Question: @Greg-Watanabe @kkoryaka Are the Sample's "Implementation notes" content in progress, not needed, or not going to be included at this time?

Usage content for "When and how to use it": I just updated [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2272%3A17640&t=XDAPPQ7AdoQhvE5b-1)'s content to match the [Google doc](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#). Please do the same in dev.

Question: @Greg-Watanabe @kkoryaka The Behavior examples in dev aren't consistent with Figma. Were these dev changes intentional or just missed? Please let us know if you'd like to walk us through your changes, or if you just need to fix them to match Figma. Thanks!
![image](https://user-images.githubusercontent.com/99768807/226066051-54d237e3-45e1-413c-b167-bfeb4d9c062d.png)

**Comment by kkoryaka** [comment] 2023-03-20 20:56
@sharon-rabang I have updated the styles. But for as far as behavior goes, you need to work with @Greg-Watanabe https://as-cdt-pub-migr-templatews-ww-p-001-dev.azurewebsites.net/components/pagination.html

**Comment by sharon-rabang** [comment] 2023-03-20 21:43
@kkoryaka The design fixes look good, thanks!

@Greg-Watanabe @extinah I'll set up a meeting for us to discuss the questions above about the Implementation notes and Behaviors.

**Comment by sharon-rabang** [comment] 2023-03-20 23:22
@Greg-Watanabe @extinah Thanks for a good meeting!

@Greg-Watanabe Here are the tasks we discussed. Please let us know when they're ready for UX review.
**Sample, Source code:** Update tab as designed in [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3586%3A36140&t=SBEcaurAoAqErWPz-1):
![image](https://user-images.githubusercontent.com/99768807/226486230-0d1dd23c-4ec0-4ef5-8842-6e40918daa3f.png)

 **Sample, Implementation notes:** Update tab with your draft notes. [Placeholder in Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=3586%3A36173&t=SBEcaurAoAqErWPz-1) and [Google doc](https://docs.google.com/document/d/1FbDHUG5MjHBwkCCwqSCEOc4s4X-l7z1WP4NHsAYO9g0/edit#)

**Behaviors table header:** Change from "Example" to "Live example"

**Components landing page:** Add [Figma pagination card](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A5622&t=XDAPPQ7AdoQhvE5b-1) with image and description

**Comment by kkoryaka** [comment] 2023-03-27 19:06
@sharon-rabang @Greg-Watanabe mentioned that he is done with this page. Please check.

**Comment by Greg-Watanabe** [comment] 2023-03-27 22:24
It makes more sense to put the javascript under implementation tab. I submitted PR #1314 for the other changes.

**Comment by sharon-rabang** [comment] 2023-03-27 22:32
@Greg-Watanabe Thank you for these:
- Sample, Source code: JS clarification. 
  - Figma and the Google doc have been updated to reflect this.
- Sample, Implementation notes: Submitting PR https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1314 for this change.
- Components landing page: Submitting PR https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1314 for this change.

**Closed by sharon-rabang** 2023-03-27 22:32 UTC
Labels: content, 👀 Candidate for DS, P1
